version: 2

references:
  container_py34: &test_container_config_py34
    docker:
      - image: circleci/python:3.4.9

  container_py36: &test_container_config_py36
    docker:
      - image: circleci/python:3.6.6

  container_py37: &test_container_config_py37
    docker:
      - image: circleci/python:3.7.0

  get_requirements: &get_requirements
    run:
      name: Install dependencies
      command: |
        pip${PYVER} install --user numpy
        pip${PYVER} install --user git+https://bitbucket.org/glotzer/libgetar.git
        pip${PYVER} install --user coverage
        pip${PYVER} install --user .

  test: &test
    run:
      name: Run unit tests
      command: |
          python${PYVER} -m coverage run -m unittest discover test -v

  build_and_test: &build_and_test
    steps:
      - checkout
      - *get_requirements
      - *test
    working_directory: ~/repo

jobs:
  test-py34:
    <<: *test_container_config_py34
    environment:
      PYVER: "3.4"
    <<: *build_and_test

  test-py36:
    <<: *test_container_config_py36
    environment:
      PYVER: "3.6"
    <<: *build_and_test

  test-py37:
    <<: *test_container_config_py37
    environment:
      PYVER: "3.7"
    <<: *build_and_test

workflows:
  version: 2
  all:
    jobs:
      - test-py34
      - test-py36
      - test-py37
